//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drone.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;installation du drone nécessite python3..
        /// </summary>
        internal static string NeedPython3 {
            get {
                return ResourceManager.GetString("NeedPython3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecté..
        /// </summary>
        internal static string Perform_PerformSock_Connecté {
            get {
                return ResourceManager.GetString("Perform_PerformSock_Connecté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion autorisée. Utilisateur : .
        /// </summary>
        internal static string Perform_PerformSock_Connexion_autorisée__Utilisateur {
            get {
                return ResourceManager.GetString("Perform_PerformSock_Connexion_autorisée__Utilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied..
        /// </summary>
        internal static string Perform_PerformSock_Denied_ {
            get {
                return ResourceManager.GetString("Perform_PerformSock_Denied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais identifiants : .
        /// </summary>
        internal static string Perform_PerformSock_Mauvais_identifiants {
            get {
                return ResourceManager.GetString("Perform_PerformSock_Mauvais_identifiants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ENOUGH MEMORY TO START CONFIG THREAD.
        /// </summary>
        internal static string Perform_PerformSock_NOT_ENOUGH_MEMORY_TO_START_CONFIG_THREAD {
            get {
                return ResourceManager.GetString("Perform_PerformSock_NOT_ENOUGH_MEMORY_TO_START_CONFIG_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///traitement msg.
        /// </summary>
        internal static string Perform_PerformSock_traitement_msg {
            get {
                return ResourceManager.GetString("Perform_PerformSock_traitement_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez l&apos;installer, et entrer ci-dessous le chemin pour y accéder (en incluant python3.exe).
        /// </summary>
        internal static string PleaseInstallAndEnterPath {
            get {
                return ResourceManager.GetString("PleaseInstallAndEnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debut phase de démarrage..
        /// </summary>
        internal static string Startup_Boot_Debut_phase_de_démarrage {
            get {
                return ResourceManager.GetString("Startup_Boot_Debut_phase_de_démarrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drone en ligne. Connexion au serveur....
        /// </summary>
        internal static string Startup_Boot_Drone_en_ligne__Connexion_au_serveur {
            get {
                return ResourceManager.GetString("Startup_Boot_Drone_en_ligne__Connexion_au_serveur", resourceCulture);
            }
        }
    }
}
