//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drone.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;installation du drone nécessite python3..
        /// </summary>
        internal static string NeedPython3 {
            get {
                return ResourceManager.GetString("NeedPython3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connecté..
        /// </summary>
        internal static string Perform_PerformSock_Connecté {
            get {
                return ResourceManager.GetString("Perform_PerformSock_Connecté", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion autorisée. Utilisateur : .
        /// </summary>
        internal static string Perform_PerformSock_Connexion_autorisée__Utilisateur {
            get {
                return ResourceManager.GetString("Perform_PerformSock_Connexion_autorisée__Utilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Denied..
        /// </summary>
        internal static string Perform_PerformSock_Denied_ {
            get {
                return ResourceManager.GetString("Perform_PerformSock_Denied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mauvais identifiants : .
        /// </summary>
        internal static string Perform_PerformSock_Mauvais_identifiants {
            get {
                return ResourceManager.GetString("Perform_PerformSock_Mauvais_identifiants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NOT ENOUGH MEMORY TO START CONFIG THREAD.
        /// </summary>
        internal static string Perform_PerformSock_NOT_ENOUGH_MEMORY_TO_START_CONFIG_THREAD {
            get {
                return ResourceManager.GetString("Perform_PerformSock_NOT_ENOUGH_MEMORY_TO_START_CONFIG_THREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///traitement msg.
        /// </summary>
        internal static string Perform_PerformSock_traitement_msg {
            get {
                return ResourceManager.GetString("Perform_PerformSock_traitement_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez l&apos;installer, et entrer ci-dessous le chemin pour y accéder (en incluant python3.exe).
        /// </summary>
        internal static string PleaseInstallAndEnterPath {
            get {
                return ResourceManager.GetString("PleaseInstallAndEnterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Echec du démarrage. Nouvelle tentative dans 3 secondes..
        /// </summary>
        internal static string Program_Main_boot_fail_new_try_in_3_seconds {
            get {
                return ResourceManager.GetString("Program_Main_boot_fail_new_try_in_3_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résolution DNS.
        /// </summary>
        internal static string Sock_init_DNS_Resolving {
            get {
                return ResourceManager.GetString("Sock_init_DNS_Resolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche de l&apos;adresse IP....
        /// </summary>
        internal static string Sock_init_Searching_IP_Address {
            get {
                return ResourceManager.GetString("Sock_init_Searching_IP_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debut phase de démarrage..
        /// </summary>
        internal static string Startup_Boot_Debut_phase_de_démarrage {
            get {
                return ResourceManager.GetString("Startup_Boot_Debut_phase_de_démarrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drone en ligne. Connexion au serveur....
        /// </summary>
        internal static string Startup_Boot_Drone_en_ligne__Connexion_au_serveur {
            get {
                return ResourceManager.GetString("Startup_Boot_Drone_en_ligne__Connexion_au_serveur", resourceCulture);
            }
        }
    }
}
